repos:
    - repo: https://github.com/ambv/black
      rev: "20.8b1"
      hooks:
          - id: black
            language_version: python3
            exclude: migrations

    - repo: https://gitlab.com/pycqa/flake8
      rev: "3.9.1"
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    flake8-bandit,
                    flake8-bugbear,
                    flake8-builtins,
                    flake8-import-order,
                    flake8-polyfill,
                ]
            exclude: ^(migrations)/|test*.py

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.2.1"
      hooks:
          - id: prettier
